# Generated by Django 5.0.4 on 2024-05-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.coremodel')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "O'lchov",
                'verbose_name_plural': "O'lchovlar",
            },
            bases=('product.coremodel',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit'),
        ),
    ]
