# Generated by Django 5.0.4 on 2024-05-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_unit_remove_product_unit_product_unit_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category_id', 'price', 'name')},
        ),
    ]
