# Generated by Django 5.0.4 on 2024-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
