# Generated by Django 5.0.4 on 2024-05-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'bugalter'), (1, 'omborchi')]),
        ),
    ]
