# Generated by Django 5.0.4 on 2024-05-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productoutput_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutput',
            name='removed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'bugalter'), (1, 'omborchi')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_number',
            field=models.CharField(max_length=13),
        ),
    ]
